services:
  - type: web
    name: visionboard
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 8090
